project:
  type: book

book:
  title: "**gloffis** tutorials"
  author: "Patricia Trambauer and Jan Verkade"
  date: today
  date-format: full
  chapters:
    - index.qmd
    - streamflow_simulations.qmd
    - medium_term_forecasts.qmd
    - seasonal_forecasts.qmd
    - seasonal_forecasts_visualization.qmd
    #- warning_levels.qmd
    #- drought_indicators.qmd
    #- summary.qmd
    #- references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: source

